# Generated by Django 5.2.6 on 2025-11-05 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0005_order_payment_reference'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='payment_reference',
            new_name='sku',
        ),
        migrations.AlterField(
            model_name='order',
            name='reference',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
