# Generated by Django 5.2.6 on 2025-11-06 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0006_rename_payment_reference_order_sku_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cart_code',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('pending', 'Pending'), ('in-progress', 'In Progress')], default='pending', max_length=20),
        ),
    ]
