# Generated by Django 5.2.6 on 2025-11-06 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0008_alter_order_cart_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cart_code',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True),
        ),
    ]
