# Generated by Django 5.2.6 on 2025-11-07 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0010_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cart_code',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='cart_code',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
