# Generated by Django 5.2.6 on 2026-06-26 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0011_alter_cart_cart_code_alter_order_cart_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cart_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
